// Generated by AI

package org.galemc.gale.util.collection;

import net.minecraft.world.entity.Entity;
import org.jetbrains.annotations.Nullable;
import java.util.NoSuchElementException;

/**
 * A highly optimized structure-of-arrays min-heap of (value: double, target: int) pairs.
 * <p>
 * - 1-based heap indexing (index 0 unused).
 * - All storage is primitive arrays; no per-entry object allocations.
 * - Log(n) operations: peekValue, popFirst, add, remove.
 * - Hole-based siftUp / siftDown; heapIndex (map) updated only when a node actually moves.
 * - Grows heap capacity by factor 1.5 when needed.
 * <p>
 * Usage guarantees (as requested by user):
 * - add(...) will never be called for a target already present.
 * - remove(target) will only be called for a present target.
 * <p>
 * Not thread-safe.
 */
public final class DoubleTargetHeap {

    // Heap arrays (1-based). slot 0 unused.
    private double[] values; // length = cap+1
    private Entity[] targets;   // length = cap+1
    private byte[] types;   // length = cap+1
    private int size;        // number of elements, 0..size

    // Map from target -> heapIndex (1..size). Implemented as open-addressing hash table.
    // All primitive arrays to avoid allocations.
    private Entity[] mapKeys;   // stored keys
    private int[] mapVals;   // stored heap indices
    private byte[] mapState; // 0 = empty, 1 = occupied
    private int mapMask;     // mask for indexing (capacity - 1)
    private int mapSize;     // number of entries in map

    private static final int DEFAULT_CAP = 16;
    private static final byte OCCUPIED = 1;
    private static final byte EMPTY = 0;

    public DoubleTargetHeap() {
        this(DEFAULT_CAP);
    }

    public DoubleTargetHeap(int initialCapacity) {
        int cap = Math.max(4, initialCapacity);
        // heap capacity is cap rounded up to power-of-two? not necessary; keep as given
        initHeap(cap);
        initMap(nextPowerOfTwo(cap * 2));
    }

    // -------------------------
    // Public API
    // -------------------------

    /**
     * Returns the value of the first (min) pair. Caller guarantees not empty.
     */
    public double peekValue() {
        return values[1];
    }

    /**
     * Returns the type of the first (min) pair. Caller guarantees not empty.
     */
    public byte peekType() {
        return types[1];
    }

    /**
     * Pops the first (min) pair and returns its target. Caller guarantees not empty.
     */
    public @Nullable Entity popFirst() {
        Entity rootTarget = targets[1];
        removeAtIndex(1);
        return rootTarget;
    }

    /**
     * Adds a (value, target) pair. Caller guarantees target not already present.
     */
    public void add(double value, Entity target, byte type) {
        ensureHeapCapacityForAdd();
        int idx = ++size;
        // hole-based siftUp
        int hole = idx;
        int parent = hole >>> 1;
        while (parent >= 1 && values[parent] > value) {
            // move parent down
            values[hole] = values[parent];
            targets[hole] = targets[parent];
            putMap(targets[hole], hole); // update map for moved parent target to new index
            types[hole] = types[parent];
            hole = parent;
            parent = hole >>> 1;
        }
        // place new element
        values[hole] = value;
        targets[hole] = target;
        types[hole] = type;
        putMap(target, hole);
    }

    /**
     * Removes the pair with the given target. Caller guarantees target present.
     */
    public void remove(Entity target) {
        int idx = getMap(target);
        // guaranteed present
        removeAtIndex(idx);
    }

    /**
     * Returns number of elements.
     */
    public int size() {
        return size;
    }

    /**
     * Returns true if empty.
     */
    public boolean isEmpty() {
        return size == 0;
    }

    // -------------------------
    // Internal helpers
    // -------------------------

    private void removeAtIndex(int idx) {
        // remove mapping for the target at idx
        Entity removedTarget = targets[idx];
        deleteMap(removedTarget);

        if (idx == size) {
            // removing last element
            size--;
            return;
        }

        // move last element into hole and then sift
        double lastVal = values[size];
        Entity lastTarget = targets[size];
        byte lastType = types[size];
        size--;

        // decide whether to sift up or down
        int parent = idx >>> 1;
        if (parent >= 1 && values[parent] > lastVal) {
            // sift up
            int hole = idx;
            while (parent >= 1 && values[parent] > lastVal) {
                values[hole] = values[parent];
                targets[hole] = targets[parent];
                putMap(targets[hole], hole);
                types[hole] = types[parent];
                hole = parent;
                parent = hole >>> 1;
            }
            values[hole] = lastVal;
            targets[hole] = lastTarget;
            putMap(lastTarget, hole);
            types[hole] = lastType;
        } else {
            // sift down
            int hole = idx;
            int half = size >>> 1; // nodes with children
            while (hole <= half) {
                int left = hole << 1;
                int right = left + 1;
                int smallest = left;
                double smallestVal = values[left];
                if (right <= size && values[right] < smallestVal) {
                    smallest = right;
                    smallestVal = values[right];
                }
                if (smallestVal >= lastVal) break;
                // move child up
                values[hole] = smallestVal;
                targets[hole] = targets[smallest];
                putMap(targets[hole], hole);
                types[hole] = types[smallest];
                hole = smallest;
            }
            values[hole] = lastVal;
            targets[hole] = lastTarget;
            putMap(lastTarget, hole);
            types[hole] = lastType;
        }
    }

    // -------------------------
    // Heap capacity management
    // -------------------------

    private void ensureHeapCapacityForAdd() {
        if (size + 1 < values.length) return;
        int oldCap = values.length - 1;
        int newCap = oldCap + (oldCap >> 1); // grow by 1.5x
        if (newCap < oldCap + 1) newCap = oldCap + 1;
        resizeHeap(newCap);
    }

    private void initHeap(int cap) {
        values = new double[cap + 1];
        targets = new Entity[cap + 1];
        types = new byte[cap + 1];
        size = 0;
    }

    private void resizeHeap(int newCap) {
        double[] newValues = new double[newCap + 1];
        Entity[] newTargets = new Entity[newCap + 1];
        byte[] newTypes = new byte[newCap + 1];
        System.arraycopy(values, 1, newValues, 1, size);
        System.arraycopy(targets, 1, newTargets, 1, size);
        System.arraycopy(types, 1, newTypes, 1, size);
        values = newValues;
        targets = newTargets;
        types = newTypes;
        // rebuild map with new capacity to keep load low and map sizing consistent
        reinitMapForHeapCapacity(newCap);
    }

    // -------------------------
    // Map implementation (target -> heapIndex)
    // Open-addressing linear probing, rehashed from heap when needed.
    // -------------------------

    private void initMap(int capacityPowerOfTwo) {
        int cap = Math.max(2, capacityPowerOfTwo);
        mapKeys = new Entity[cap];
        mapVals = new int[cap];
        mapState = new byte[cap];
        mapMask = cap - 1;
        mapSize = 0;
    }

    private void reinitMapForHeapCapacity(int heapCap) {
        // choose map capacity as next power of two >= heapCap * 2
        int desired = Math.max(2, nextPowerOfTwo(heapCap * 2));
        initMap(desired);
        // reinsert existing heap entries
        for (int i = 1; i <= size; i++) {
            putMapInternal(targets[i], i);
        }
    }

    private static int nextPowerOfTwo(int v) {
        int x = v - 1;
        x |= x >>> 1;
        x |= x >>> 2;
        x |= x >>> 4;
        x |= x >>> 8;
        x |= x >>> 16;
        return (x < 0) ? 1 : (x + 1);
    }

    private int mixInt(Entity e) {
        int x = e.getId();
        return Integer.rotateRight(x * 0x9E3779B9, 16) ^ (x >>> 16);
    }

    /**
     * Put mapping target -> heapIndex. Overwrites existing if present.
     */
    private void putMap(Entity key, int heapIndex) {
        // grow map if load factor > 0.5
        if ((mapSize << 1) >= mapKeys.length) {
            rehashMap(mapKeys.length << 1);
        }
        putMapInternal(key, heapIndex);
    }

    private void putMapInternal(Entity key, int heapIndex) {
        int mask = mapMask;
        int idx = mixInt(key) & mask;
        while (mapState[idx] == OCCUPIED) {
            if (mapKeys[idx] == key) {
                mapVals[idx] = heapIndex;
                return;
            }
            idx = (idx + 1) & mask;
        }
        mapState[idx] = OCCUPIED;
        mapKeys[idx] = key;
        mapVals[idx] = heapIndex;
        mapSize++;
    }

    /**
     * Get heap index for key. Caller assumes key present.
     */
    private int getMap(Entity key) {
        int mask = mapMask;
        int idx = mixInt(key) & mask;
        while (true) {
            if (mapState[idx] == EMPTY) {
                // not found
                throw new NoSuchElementException("target not found in map: " + key);
            }
            if (mapState[idx] == OCCUPIED && mapKeys[idx] == key) {
                return mapVals[idx];
            }
            idx = (idx + 1) & mask;
        }
    }

    /**
     * Delete mapping for key. Caller assumes key present.
     */
    private void deleteMap(Entity key) {
        int mask = mapMask;
        int idx = mixInt(key) & mask;
        while (true) {
            if (mapState[idx] == EMPTY) {
                throw new NoSuchElementException("target not found in map: " + key);
            }
            if (mapState[idx] == OCCUPIED && mapKeys[idx] == key) {
                // remove this slot and re-insert subsequent cluster
                mapState[idx] = EMPTY;
                mapSize--;
                idx = (idx + 1) & mask;
                while (mapState[idx] == OCCUPIED) {
                    Entity reKey = mapKeys[idx];
                    int reVal = mapVals[idx];
                    mapState[idx] = EMPTY;
                    mapSize--;
                    putMapInternal(reKey, reVal);
                    idx = (idx + 1) & mask;
                }
                return;
            }
            idx = (idx + 1) & mask;
        }
    }

    private void rehashMap(int newCapacity) {
        int cap = nextPowerOfTwo(newCapacity);
        Entity[] oldKeys = mapKeys;
        int[] oldVals = mapVals;
        byte[] oldState = mapState;
        initMap(cap);
        for (int i = 0; i < oldKeys.length; i++) {
            if (oldState[i] == OCCUPIED) {
                putMapInternal(oldKeys[i], oldVals[i]);
            }
        }
    }

    // -------------------------
    // For debugging (optional)
    // -------------------------
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("DoubleTargetHeap[size=").append(size).append("]{");
        for (int i = 1; i <= size; i++) {
            if (i > 1) sb.append(", ");
            sb.append("(").append(values[i]).append(",").append(targets[i].getId()).append(",").append(types[i]).append(")");
        }
        sb.append("}");
        return sb.toString();
    }

}
