name: Build Gale
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    # Always run on PRs if the source branch is on someone else's repo, and otherwise, only run if the last commit does not start with [ci-skip]
    if: ${{ (github.event_name != 'pull_request' && !contains(github.event.commits[0].message, '[ci-skip]')) || github.repository != github.event.pull_request.head.repo.full_name }}
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Git user details
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew applyAllPatches
      - name: Create Paperclip jar
        run: ./gradlew :gale-server:createPaperclipJar --stacktrace
      - name: Rename and move JAR
        run: |
          MC_VERSION=$(grep -E '^mcVersion=' gradle.properties | cut -d= -f2 | tr -d '[:space:]')
          mv gale-server/build/libs/gale-paperclip-*.jar gale-${MC_VERSION}-${{ github.run_number }}.jar
      - name: Upload Paperclip jar
        uses: actions/upload-artifact@v7
        with:
          name: Gale server JAR
          path: gale-*.jar
          archive: false
