name: Build Gale
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    # Always run on PRs if the source branch is on someone else's repo, and otherwise, only run if the last commit does not start with [ci-skip]
    if: ${{ (github.event_name != 'pull_request' && !contains(github.event.commits[0].message, '[ci-skip]')) || github.repository != github.event.pull_request.head.repo.full_name }}
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Configure Git user details
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew applyAllPatches
      - name: Create Paperclip jar
        run: ./gradlew :gale-server:createPaperclipJar --stacktrace
      - name: Rename and move JAR
        run: mv gale-server/build/libs/gale-paperclip-*.jar gale-$(basename gale-server/build/libs/gale-paperclip-*.jar | sed -E 's/^gale-paperclip-(.*)\.jar$/\1/').jar
      - name: Upload Paperclip jar
        uses: actions/upload-artifact@v4
        with:
          name: Gale
          path: gale-*.jar
          archive: false
